name: ZMusic
main: me.zhenxin.zmusic.bukkit.ZMusicBukkit
version: ${version}
api-version: 1.13
author: 真心
description: 真心音乐系统
softdepend:
  - ViaVersion
  - PlaceholderAPI
  - Vault
  - Yum
  - CMI
commands:
  zm:
    usage: /zm help
    aliases:
      - zmusic
      - music
permissions:
  zmusic.use:
    default: true
  zmusic.bypass:
    default: op
  zmusic.admin:
    default: op
