[versions]
taboolib = "6.0.10-121"
spigot = "1.19.4-R0.1-SNAPSHOT"
bungeecord = "1.19-R0.1-SNAPSHOT"
velocity = "3.1.1"
hutool = "5.8.18"
nashorn = "15.4"
nashorn_sandbox = "0.2.5"
netty = "4.1.89.Final"
placeholderapi = "2.11.3"

[libraries]
# Platform API
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
# hutool
hutool_core = { module = "cn.hutool:hutool-core", version.ref = "hutool" }
hutool_http = { module = "cn.hutool:hutool-http", version.ref = "hutool" }
hutool_json = { module = "cn.hutool:hutool-json", version.ref = "hutool" }
# nashorn
nashorn = { module = "org.openjdk.nashorn:nashorn-core", version.ref = "nashorn" }
nashorn_sandbox = { module = "org.javadelight:delight-nashorn-sandbox", version.ref = "nashorn_sandbox" }
# netty
netty_buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
# PAPI
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

[bundles]
platform = ["spigot", "bungeecord", "velocity"]
hutool = ["hutool_core", "hutool_http", "hutool_json"]
nashorn = ["nashorn", "nashorn_sandbox"]