# 配置文件版本(请勿修改)
version: 1

# 是否开启调试模式
debug: false

# 点歌设置
music:
  # 点歌扣除的金币(设置为0则不扣除)
  # 拥有zmusic.bypass的玩家无视扣除
  money: 10
  # 点歌的冷却时间(设置为0则无冷却)
  # 拥有zmusic.bypass的玩家无视冷却
  cooldown: 5

# 歌词设置
lyric:
  # 是否启用歌词
  enable: true
  # 以下为显示方式设置，可同时启用
  # 是否使用BossBar显示歌词(Mod服请关闭，不支持BossBar)
  # 需要前置插件BossBarAPI
  bossBar: true
  # 是否使用ActionBar显示歌词
  # 需要前置插件ActionBarAPI
  actionBar: false
  # 是否使用Title显示歌词
  subTitle: false
  # 是否使用聊天信息显示歌词
  chatMessage: false