name: ZMusic
main: cn.iqianye.MinecraftPlugins.ZMusic.Main
version: 0.3-beta
author: 真心
description: 真心音乐系统
depend:
  - AudioBuffer
softdepend:
  - ActionBarAPI
  - BossBarAPI
  - PlaceholderAPI
commands:
  zm:
    usage: /zm help
    description: 主命令
permissions:
  zmusic.use:
    default: true
    description: 普通玩家使用权限
  zmusic.bypass:
    default: false
    description: 绕过部分配置权限
  zmusic.admin:
    default: op
    description: 管理员权限