name: Bridge Release

on:
  push:
    tags:
      - 'bridge-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :zmusic-bridge:clean zmusic-bridge:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'ZMusic Bridge'
          path: zmusic-bridge/build/libs/ZMusicBridge*.jar
