name: Stable Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :zmusic-plugin:clean zmusic-plugin:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'ZMusic'
          path: zmusic-plugin/build/libs/ZMusic*all.jar
