name: Stable Release
on:
  push:
    branches:
      - '3.0'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'ZMusic'
          path: build/libs/ZMusic*all.jar
